---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: <gcp_project_id>
      gcp_cred_kind: serviceaccount
      gcp_cred_file: <cred_file>
      zone: "us-central1-a"
      region: "us-central1"
      http_host: "test-vm"

  tasks:
   - name: create a disk
     google.cloud.gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 30
         source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk1
   - name: create a instance
     google.cloud.gcp_compute_instance:
         state: present
         name: test-vm
         machine_type: f1-micro
         tags: "http-server"
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk1 }}"
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance1
   - name: install apache2
     apt: name=apache2 update_cache=yes state=latest
   - name: swap index.html
     file:
         src: "files/index.html.j2"
         dest: "/var/www/html/index.html"
         notify: restart-apache2

- handlers:
        - name : restart-apache2
          service:
               name: apache2
               state: restarted


       

